appName: noremains
namespace: noremains

replicaCount: 1

persistence:
  hostPath: /mnt/noremains

image:
  repository: php
  tag: 8.2-apache
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: noremains.purplebelly.local
      paths:
        - /
  tls: []