apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-code
  namespace: {{ .Values.namespace }}
data:
  index.php: |
    <?php
      header('Content-Type: application/json');
      header('Access-Control-Allow-Origin: *');
      $host = $_SERVER['HTTP_HOST'];
      $response = [
          "latest_version" => "1.0.3",
          "download_url" => "http://" . $host . "/update_package.zip",
          "broadcast" => "<h3>&nbsp;Latest Transmissions:</h3><ul><li>> [NOV 25]: Happy Birthday, Sammy!</li><li>> [NOV 26]: Happy Birthday, Adddie!</li></ul>"
      ];

      echo json_encode($response, JSON_UNESCAPED_SLASHES);
      exit;
    ?>